name: daelim_class
description: "3학년 2학기 수업"
publish_to: "none"

version: 1.0.0+1

environment:
    sdk: ^3.5.1

dependencies:
    flutter:
        sdk: flutter

    cupertino_icons: ^1.0.8

    easy_extension:
        git:
            url: https://github.com/scadasystems/Easy-Extension.git
    flex_color_scheme: ^7.3.1
    http:

dev_dependencies:
    flutter_test:
        sdk: flutter

    flutter_lints: ^4.0.0

flutter:
    uses-material-design: true
